name: .NET

on:
  push:
    branches: [ master, Cours12 ]
  pull_request:
    branches: [ master, Cours12 ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./CleanArchitectureDemo
      run: dotnet restore
    - name: Build
      working-directory: ./CleanArchitectureDemo
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./CleanArchitectureDemo
      run: dotnet test --no-build --verbosity normal
